=== e-gleba/world_conqueror_4_ru/patches/enable_all/schemas/ArmySubTypeSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "ArmySubTypeSettings.json",
  "title": "ArmySubTypeSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 101,
        "maximum": 136
      },
      "Army": {
        "type": "integer",
        "minimum": 51,
        "maximum": 96
      },
      "SubType": {
        "type": "integer",
        "minimum": 201,
        "maximum": 504,
        "enum": [
          201,
          202,
          203,
          301,
          302,
          303,
          401,
          402,
          403,
          404,
          501,
          502,
          503,
          504
        ]
      },
      "AirTransportation": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1,
        "enum": [
          0,
          1
        ]
      },
      "Tunnelling": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1,
        "enum": [
          0,
          1
        ]
      }
    },
    "required": [
      "Id",
      "Army",
      "SubType",
      "AirTransportation",
      "Tunnelling"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/ArmySubTypeSettings.json
[
{"Id":101,"Army":51,"SubType":301,"AirTransportation":1,"Tunnelling":1},
{"Id":102,"Army":52,"SubType":301,"AirTransportation":0,"Tunnelling":0},
{"Id":103,"Army":53,"SubType":302,"AirTransportation":0,"Tunnelling":1},
{"Id":104,"Army":54,"SubType":202,"AirTransportation":0,"Tunnelling":1},
{"Id":105,"Army":55,"SubType":203,"AirTransportation":0,"Tunnelling":0},
{"Id":106,"Army":56,"SubType":203,"AirTransportation":0,"Tunnelling":0},
{"Id":107,"Army":60,"SubType":401,"AirTransportation":0,"Tunnelling":0},
{"Id":108,"Army":61,"SubType":403,"AirTransportation":0,"Tunnelling":0},
{"Id":109,"Army":64,"SubType":301,"AirTransportation":1,"Tunnelling":1},
{"Id":110,"Army":65,"SubType":203,"AirTransportation":0,"Tunnelling":0},
{"Id":111,"Army":66,"SubType":302,"AirTransportation":0,"Tunnelling":1},
{"Id":112,"Army":67,"SubType":403,"AirTransportation":0,"Tunnelling":0},
{"Id":113,"Army":68,"SubType":404,"AirTransportation":0,"Tunnelling":0},
{"Id":114,"Army":70,"SubType":404,"AirTransportation":0,"Tunnelling":0},
{"Id":115,"Army":74,"SubType":203,"AirTransportation":0,"Tunnelling":0},
{"Id":116,"Army":75,"SubType":401,"AirTransportation":0,"Tunnelling":0},
{"Id":117,"Army":79,"SubType":301,"AirTransportation":0,"Tunnelling":1},
{"Id":118,"Army":80,"SubType":203,"AirTransportation":0,"Tunnelling":0},
{"Id":119,"Army":81,"SubType":402,"AirTransportation":0,"Tunnelling":0},
{"Id":120,"Army":83,"SubType":203,"AirTransportation":0,"Tunnelling":0},
{"Id":121,"Army":86,"SubType":303,"AirTransportation":0,"Tunnelling":0},
{"Id":122,"Army":87,"SubType":402,"AirTransportation":0,"Tunnelling":0},
{"Id":123,"Army":88,"SubType":201,"AirTransportation":1,"Tunnelling":1},
{"Id":124,"Army":89,"SubType":301,"AirTransportation":1,"Tunnelling":1},
{"Id":125,"Army":91,"SubType":302,"AirTransportation":0,"Tunnelling":1},
{"Id":126,"Army":92,"SubType":203,"AirTransportation":0,"Tunnelling":0},
{"Id":127,"Army":57,"SubType":501,"AirTransportation":0,"Tunnelling":0},
{"Id":128,"Army":58,"SubType":503,"AirTransportation":0,"Tunnelling":0},
{"Id":129,"Army":59,"SubType":502,"AirTransportation":0,"Tunnelling":0},
{"Id":130,"Army":69,"SubType":503,"AirTransportation":0,"Tunnelling":0},
{"Id":131,"Army":71,"SubType":503,"AirTransportation":0,"Tunnelling":0},
{"Id":132,"Army":72,"SubType":501,"AirTransportation":0,"Tunnelling":0},
{"Id":133,"Army":84,"SubType":504,"AirTransportation":0,"Tunnelling":0},
{"Id":134,"Army":93,"SubType":301,"AirTransportation":1,"Tunnelling":1},
{"Id":135,"Army":94,"SubType":201,"AirTransportation":1,"Tunnelling":1},
{"Id":136,"Army":96,"SubType":203,"AirTransportation":0,"Tunnelling":0}
]
