=== e-gleba/world_conqueror_4_ru/patches/enable_all/schemas/BuildingSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "BuildingSettings.json",
  "title": "BuildingSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 2,
        "maximum": 34,
        "enum": [
          2,
          3,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          21,
          22,
          23,
          31,
          32,
          33,
          34
        ]
      },
      "Name": {
        "type": "string",
        "minLength": 2,
        "maxLength": 3,
        "enum": [
          "中城市",
          "军港1",
          "军港2",
          "军港3",
          "军港4",
          "大城市",
          "大工厂",
          "大都市",
          "小城市",
          "小镇",
          "核电站",
          "炼油厂",
          "风车",
          "首都1",
          "首都2",
          "首都3",
          "首都4",
          "首都5"
        ]
      },
      "Type": {
        "type": "integer",
        "minimum": 1,
        "maximum": 4,
        "enum": [
          1,
          2,
          3,
          4
        ]
      },
      "ProduceMoney": {
        "type": "integer",
        "minimum": 0,
        "maximum": 12,
        "enum": [
          0,
          10,
          12
        ]
      },
      "ProduceGear": {
        "type": "integer",
        "minimum": 0,
        "maximum": 28,
        "enum": [
          0,
          6,
          12,
          28
        ]
      },
      "ProduceAtomic": {
        "type": "integer",
        "minimum": 0,
        "maximum": 5,
        "enum": [
          0,
          5
        ]
      },
      "ArmyId": {
        "type": "integer",
        "minimum": 0,
        "maximum": 109005,
        "enum": [
          0,
          109001,
          109002,
          109003,
          109004,
          109005
        ]
      },
      "FacilityId": {
        "type": "integer",
        "minimum": 0,
        "maximum": 20704,
        "enum": [
          0,
          20001,
          20002,
          20003,
          20004,
          20005,
          20006,
          20007,
          20008,
          20009,
          20701,
          20702,
          20703,
          20704
        ]
      },
      "ResName": {
        "type": [
          "null",
          "null"
        ]
      },
      "StyleCount": {
        "type": "integer",
        "minimum": 0,
        "maximum": 0,
        "enum": [
          0
        ]
      },
      "MeritExp": {
        "type": "integer",
        "minimum": 0,
        "maximum": 60,
        "enum": [
          0,
          20,
          30,
          40,
          50,
          60
        ]
      }
    },
    "required": [
      "Id",
      "Name",
      "Type",
      "ProduceMoney",
      "ProduceGear",
      "ProduceAtomic",
      "ArmyId",
      "FacilityId",
      "StyleCount",
      "MeritExp"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/BuildingSettings.json
[
{"Id":2,"Name":"风车","Type":1,"ProduceMoney":12,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":0,"FacilityId":0,"ResName":null,"StyleCount":0,"MeritExp":0},
{"Id":3,"Name":"小镇","Type":1,"ProduceMoney":12,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":0,"FacilityId":0,"ResName":null,"StyleCount":0,"MeritExp":0},
{"Id":11,"Name":"小城市","Type":2,"ProduceMoney":0,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":109001,"FacilityId":20001,"ResName":null,"StyleCount":0,"MeritExp":20},
{"Id":12,"Name":"中城市","Type":2,"ProduceMoney":0,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":109002,"FacilityId":20002,"ResName":null,"StyleCount":0,"MeritExp":30},
{"Id":13,"Name":"大城市","Type":2,"ProduceMoney":0,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":109003,"FacilityId":20003,"ResName":null,"StyleCount":0,"MeritExp":40},
{"Id":14,"Name":"大都市","Type":2,"ProduceMoney":0,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":109004,"FacilityId":20004,"ResName":null,"StyleCount":0,"MeritExp":50},
{"Id":15,"Name":"首都1","Type":2,"ProduceMoney":0,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":109005,"FacilityId":20005,"ResName":null,"StyleCount":0,"MeritExp":60},
{"Id":16,"Name":"首都2","Type":2,"ProduceMoney":0,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":109005,"FacilityId":20006,"ResName":null,"StyleCount":0,"MeritExp":60},
{"Id":17,"Name":"首都3","Type":2,"ProduceMoney":0,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":109005,"FacilityId":20007,"ResName":null,"StyleCount":0,"MeritExp":60},
{"Id":18,"Name":"首都4","Type":2,"ProduceMoney":0,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":109005,"FacilityId":20008,"ResName":null,"StyleCount":0,"MeritExp":60},
{"Id":19,"Name":"首都5","Type":2,"ProduceMoney":0,"ProduceGear":0,"ProduceAtomic":0,"ArmyId":109005,"FacilityId":20009,"ResName":null,"StyleCount":0,"MeritExp":60},
{"Id":21,"Name":"炼油厂","Type":3,"ProduceMoney":0,"ProduceGear":6,"ProduceAtomic":0,"ArmyId":0,"FacilityId":0,"ResName":null,"StyleCount":0,"MeritExp":0},
{"Id":22,"Name":"大工厂","Type":3,"ProduceMoney":0,"ProduceGear":12,"ProduceAtomic":0,"ArmyId":0,"FacilityId":0,"ResName":null,"StyleCount":0,"MeritExp":0},
{"Id":23,"Name":"核电站","Type":3,"ProduceMoney":0,"ProduceGear":28,"ProduceAtomic":5,"ArmyId":0,"FacilityId":0,"ResName":null,"StyleCount":0,"MeritExp":0},
{"Id":31,"Name":"军港1","Type":4,"ProduceMoney":10,"ProduceGear":6,"ProduceAtomic":0,"ArmyId":0,"FacilityId":20701,"ResName":null,"StyleCount":0,"MeritExp":20},
{"Id":32,"Name":"军港2","Type":4,"ProduceMoney":10,"ProduceGear":6,"ProduceAtomic":0,"ArmyId":0,"FacilityId":20702,"ResName":null,"StyleCount":0,"MeritExp":20},
{"Id":33,"Name":"军港3","Type":4,"ProduceMoney":10,"ProduceGear":6,"ProduceAtomic":0,"ArmyId":0,"FacilityId":20703,"ResName":null,"StyleCount":0,"MeritExp":20},
{"Id":34,"Name":"军港4","Type":4,"ProduceMoney":10,"ProduceGear":6,"ProduceAtomic":0,"ArmyId":0,"FacilityId":20704,"ResName":null,"StyleCount":0,"MeritExp":20}
]
