=== e-gleba/world_conqueror_4_ru/patches/enable_all/schemas/ConquerSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "ConquerSettings.json",
  "title": "ConquerSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9
        ]
      },
      "Name": {
        "type": "string",
        "minLength": 6,
        "maxLength": 6,
        "enum": [
          "1939.9",
          "1943.3",
          "1950.1",
          "1960.1",
          "1980.1"
        ]
      },
      "NormalId": {
        "type": "integer",
        "minimum": 0,
        "maximum": 4,
        "enum": [
          0,
          1,
          2,
          3,
          4
        ]
      },
      "Difficulty": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1,
        "enum": [
          0,
          1
        ]
      },
      "StartDate": {
        "type": "array",
        "minItems": 2,
        "maxItems": 2
      },
      "Open": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1,
        "enum": [
          0,
          1
        ]
      },
      "Visible": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1,
        "enum": [
          1
        ]
      }
    },
    "required": [
      "Id",
      "Name",
      "NormalId",
      "Difficulty",
      "StartDate",
      "Open",
      "Visible"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/diff_mod/assets/data/ConquerSettings.json
[
  {
    "Id": 1,
    "Name": "1939.9",
    "NormalId": 0,
    "Difficulty": 0,
    "StartDate": [
      1939,
      9
    ],
    "Open": 1,
    "Visible": 1
  },
  {
    "Id": 2,
    "Name": "1943.3",
    "NormalId": 0,
    "Difficulty": 0,
    "StartDate": [
      1943,
      3
    ],
    "Open": 1,
    "Visible": 1
  },
  {
    "Id": 3,
    "Name": "1950.1",
    "NormalId": 0,
    "Difficulty": 0,
    "StartDate": [
      1950,
      1
    ],
    "Open": 1,
    "Visible": 1
  },
  {
    "Id": 4,
    "Name": "1980.1",
    "NormalId": 0,
    "Difficulty": 0,
    "StartDate": [
      1980,
      1
    ],
    "Open": 1,
    "Visible": 1
  },
  {
    "Id": 5,
    "Name": "1939.9",
    "NormalId": 1,
    "Difficulty": 1,
    "StartDate": [
      1939,
      9
    ],
    "Open": 1,
    "Visible": 1
  },
  {
    "Id": 6,
    "Name": "1943.3",
    "NormalId": 2,
    "Difficulty": 1,
    "StartDate": [
      1943,
      3
    ],
    "Open": 1,
    "Visible": 1
  },
  {
    "Id": 7,
    "Name": "1950.1",
    "NormalId": 3,
    "Difficulty": 1,
    "StartDate": [
      1950,
      1
    ],
    "Open": 1,
    "Visible": 1
  },
  {
    "Id": 8,
    "Name": "1960.1",
    "NormalId": 4,
    "Difficulty": 1,
    "StartDate": [
      1960,
      1
    ],
    "Open": 1,
    "Visible": 1
  },
  {
    "Id": 9,
    "Name": "1980.1",
    "NormalId": 4,
    "Difficulty": 1,
    "StartDate": [
      1980,
      1
    ],
    "Open": 1,
    "Visible": 1
  }
]
