=== e-gleba/world_conqueror_4_ru/patches/enable_all/schemas/CorpsSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "CorpsSettings.json",
  "title": "CorpsSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Lv": {
        "type": "integer",
        "minimum": -1,
        "maximum": 50
      },
      "NeedExp": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100000,
        "enum": [
          0,
          1000,
          2000,
          5000,
          25000,
          100000
        ]
      },
      "UnlockLegionLv": {
        "type": "integer",
        "minimum": 0,
        "maximum": 11,
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11
        ]
      },
      "ExchangeTimes": {
        "type": "integer",
        "minimum": 0,
        "maximum": 6,
        "enum": [
          0,
          1,
          2,
          3,
          6
        ]
      },
      "SeniorSeat": {
        "type": "integer",
        "minimum": 0,
        "maximum": 31
      },
      "JuniorSeat": {
        "type": "integer",
        "minimum": 0,
        "maximum": 6,
        "enum": [
          0,
          2,
          3,
          4,
          5,
          6
        ]
      },
      "QuestQuantity": {
        "type": "integer",
        "minimum": 0,
        "maximum": 3,
        "enum": [
          0,
          3
        ]
      },
      "QuestLv": {
        "type": "array",
        "minItems": 0,
        "maxItems": 3
      },
      "QuestProbability": {
        "type": "array",
        "minItems": 0,
        "maxItems": 3
      },
      "InvasionQuantity": {
        "type": "integer",
        "minimum": 0,
        "maximum": 3,
        "enum": [
          0,
          3
        ]
      },
      "InvasionLv": {
        "type": "array",
        "minItems": 0,
        "maxItems": 3
      },
      "InvasionProbability": {
        "type": "array",
        "minItems": 0,
        "maxItems": 3
      }
    },
    "required": [
      "Lv",
      "NeedExp",
      "UnlockLegionLv",
      "ExchangeTimes",
      "SeniorSeat",
      "JuniorSeat",
      "QuestQuantity",
      "QuestLv",
      "QuestProbability",
      "InvasionQuantity",
      "InvasionLv",
      "InvasionProbability"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/diff_mod/assets/data/CorpsSettings.json
[
  {
    "Lv": 1,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 3,
    "JuniorSeat": 2,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      2,
      3
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 2,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 3,
    "JuniorSeat": 2,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      2,
      3
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 3,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 4,
    "JuniorSeat": 2,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      2,
      3
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 4,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 4,
    "JuniorSeat": 2,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      2,
      3
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 5,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 5,
    "JuniorSeat": 3,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      2,
      3
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 6,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 5,
    "JuniorSeat": 3,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      2,
      3
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 7,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 6,
    "JuniorSeat": 3,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      2,
      3
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 8,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 6,
    "JuniorSeat": 3,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      2,
      3
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 9,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 7,
    "JuniorSeat": 3,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      3,
      5
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 10,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 7,
    "JuniorSeat": 4,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      3,
      5
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 11,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 8,
    "JuniorSeat": 4,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      3,
      5
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 12,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 8,
    "JuniorSeat": 4,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      1,
      3,
      5
    ],
    "InvasionProbability": [
      100,
      0,
      0
    ]
  },
  {
    "Lv": 13,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 9,
    "JuniorSeat": 4,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      2,
      4,
      6
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 14,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 9,
    "JuniorSeat": 4,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      2,
      4,
      6
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 15,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 1,
    "SeniorSeat": 10,
    "JuniorSeat": 5,
    "QuestQuantity": 3,
    "QuestLv": [
      1,
      3,
      7
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      2,
      4,
      6
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 16,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 2,
    "SeniorSeat": 10,
    "JuniorSeat": 5,
    "QuestQuantity": 3,
    "QuestLv": [
      2,
      4,
      8
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      2,
      4,
      6
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 17,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 2,
    "SeniorSeat": 11,
    "JuniorSeat": 5,
    "QuestQuantity": 3,
    "QuestLv": [
      2,
      4,
      8
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      2,
      4,
      7
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 18,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 2,
    "SeniorSeat": 11,
    "JuniorSeat": 5,
    "QuestQuantity": 3,
    "QuestLv": [
      2,
      4,
      8
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      2,
      4,
      7
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 19,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 2,
    "SeniorSeat": 12,
    "JuniorSeat": 5,
    "QuestQuantity": 3,
    "QuestLv": [
      2,
      4,
      8
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      2,
      4,
      7
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 20,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 2,
    "SeniorSeat": 12,
    "JuniorSeat": 6,
    "QuestQuantity": 3,
    "QuestLv": [
      2,
      4,
      8
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      2,
      4,
      7
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 21,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 2,
    "SeniorSeat": 13,
    "JuniorSeat": 6,
    "QuestQuantity": 3,
    "QuestLv": [
      2,
      4,
      8
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      3,
      5,
      9
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 22,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 2,
    "SeniorSeat": 13,
    "JuniorSeat": 6,
    "QuestQuantity": 3,
    "QuestLv": [
      2,
      4,
      8
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      3,
      5,
      9
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 23,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 2,
    "SeniorSeat": 14,
    "JuniorSeat": 6,
    "QuestQuantity": 3,
    "QuestLv": [
      2,
      4,
      8
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      3,
      5,
      9
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 24,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 2,
    "SeniorSeat": 14,
    "JuniorSeat": 6,
    "QuestQuantity": 3,
    "QuestLv": [
      2,
      4,
      8
    ],
    "QuestProbability": [
      50,
      30,
      20
    ],
    "InvasionQuantity": 3,
    "InvasionLv": [
      3,
      5,
      9
    ],
    "InvasionProbability": [
      50,
      30,
      20
    ]
  },
  {
    "Lv": 25,
    "NeedExp": 0,
    "UnlockLegionLv": 0,
    "ExchangeTimes": 2,
    "SeniorSeat": 15,
