=== e-gleba/world_conqueror_4_ru/patches/enable_all/schemas/GeneralTitleSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "GeneralTitleSettings.json",
  "title": "GeneralTitleSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 1009,
        "maximum": 1062,
        "enum": [
          1009,
          1018,
          1019,
          1031,
          1049,
          1050,
          1051,
          1062
        ]
      },
      "GeneralId": {
        "type": "integer",
        "minimum": 1009,
        "maximum": 1062,
        "enum": [
          1009,
          1018,
          1019,
          1031,
          1049,
          1050,
          1051,
          1062
        ]
      },
      "EliteType": {
        "type": "integer",
        "minimum": 1,
        "maximum": 4,
        "enum": [
          1,
          2,
          3,
          4
        ]
      },
      "AddHpPercent": {
        "type": "integer",
        "minimum": 0,
        "maximum": 20,
        "enum": [
          0,
          20
        ]
      },
      "AddAttack": {
        "type": "integer",
        "minimum": 0,
        "maximum": 18,
        "enum": [
          0,
          12,
          18
        ]
      },
      "AddDefense": {
        "type": "integer",
        "minimum": 0,
        "maximum": 12,
        "enum": [
          0,
          12
        ]
      },
      "AddMRange": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1,
        "enum": [
          0,
          1
        ]
      },
      "AddMobility": {
        "type": "integer",
        "minimum": 0,
        "maximum": 2,
        "enum": [
          0,
          2
        ]
      },
      "AddCriChange": {
        "type": "integer",
        "minimum": 0,
        "maximum": 10,
        "enum": [
          0,
          10
        ]
      },
      "AddCriDamage": {
        "type": "integer",
        "minimum": 0,
        "maximum": 35,
        "enum": [
          0,
          25,
          35
        ]
      }
    },
    "required": [
      "Id",
      "GeneralId",
      "EliteType",
      "AddHpPercent",
      "AddAttack",
      "AddDefense",
      "AddMRange",
      "AddMobility",
      "AddCriChange",
      "AddCriDamage"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/GeneralTitleSettings.json
[
{"Id":1049,"GeneralId":1049,"EliteType":2,"AddHpPercent":0,"AddAttack":12,"AddDefense":0,"AddMRange":0,"AddMobility":0,"AddCriChange":10,"AddCriDamage":0},
{"Id":1018,"GeneralId":1018,"EliteType":3,"AddHpPercent":20,"AddAttack":18,"AddDefense":0,"AddMRange":0,"AddMobility":0,"AddCriChange":0,"AddCriDamage":0},
{"Id":1062,"GeneralId":1062,"EliteType":1,"AddHpPercent":0,"AddAttack":18,"AddDefense":12,"AddMRange":0,"AddMobility":0,"AddCriChange":0,"AddCriDamage":0},
{"Id":1050,"GeneralId":1050,"EliteType":2,"AddHpPercent":0,"AddAttack":18,"AddDefense":0,"AddMRange":0,"AddMobility":0,"AddCriChange":0,"AddCriDamage":35},
{"Id":1031,"GeneralId":1031,"EliteType":4,"AddHpPercent":0,"AddAttack":18,"AddDefense":0,"AddMRange":1,"AddMobility":0,"AddCriChange":0,"AddCriDamage":0},
{"Id":1009,"GeneralId":1009,"EliteType":2,"AddHpPercent":0,"AddAttack":12,"AddDefense":0,"AddMRange":0,"AddMobility":2,"AddCriChange":0,"AddCriDamage":0},
{"Id":1051,"GeneralId":1051,"EliteType":2,"AddHpPercent":0,"AddAttack":0,"AddDefense":0,"AddMRange":0,"AddMobility":2,"AddCriChange":0,"AddCriDamage":25},
{"Id":1019,"GeneralId":1019,"EliteType":3,"AddHpPercent":0,"AddAttack":12,"AddDefense":0,"AddMRange":0,"AddMobility":0,"AddCriChange":10,"AddCriDamage":0}
]
