=== e-gleba/world_conqueror_4_ru/patches/enable_all/schemas/LoginRewardSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "LoginRewardSettings.json",
  "title": "LoginRewardSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 1,
        "maximum": 14,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14
        ]
      },
      "Medals": {
        "type": "integer",
        "minimum": 0,
        "maximum": 600,
        "enum": [
          0,
          500,
          600
        ]
      },
      "PrizeGeneralId": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1072,
        "enum": [
          0,
          1072
        ]
      },
      "PrizeGold": {
        "type": "integer",
        "minimum": 0,
        "maximum": 60000,
        "enum": [
          0,
          60000
        ]
      },
      "PrizeIndustry": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15000,
        "enum": [
          0,
          15000
        ]
      },
      "PrizeEnergy": {
        "type": "integer",
        "minimum": 0,
        "maximum": 5000,
        "enum": [
          0,
          5000
        ]
      },
      "PrizeTech": {
        "type": "integer",
        "minimum": 0,
        "maximum": 500,
        "enum": [
          0,
          500
        ]
      },
      "PrizeMerit": {
        "type": "integer",
        "minimum": 0,
        "maximum": 50,
        "enum": [
          0,
          50
        ]
      },
      "PrizeDecoration": {
        "type": "integer",
        "minimum": 0,
        "maximum": 0,
        "enum": [
          0
        ]
      },
      "GeneralMedal": {
        "type": "array",
        "minItems": 0,
        "maxItems": 2
      },
      "Elite": {
        "type": "integer",
        "minimum": 0,
        "maximum": 0,
        "enum": [
          0
        ]
      },
      "Item": {
        "type": "array",
        "minItems": 0,
        "maxItems": 2
      }
    },
    "required": [
      "Id",
      "Medals",
      "PrizeGeneralId",
      "PrizeGold",
      "PrizeIndustry",
      "PrizeEnergy",
      "PrizeTech",
      "PrizeMerit",
      "PrizeDecoration",
      "GeneralMedal",
      "Elite",
      "Item"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/LoginRewardSettings.json
[
{"Id":1,"Medals":0,"PrizeGeneralId":0,"PrizeGold":60000,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[],"Elite":0,"Item":[]},
{"Id":2,"Medals":500,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[],"Elite":0,"Item":[]},
{"Id":3,"Medals":0,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":15000,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[],"Elite":0,"Item":[]},
{"Id":4,"Medals":0,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":5000,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[],"Elite":0,"Item":[]},
{"Id":5,"Medals":0,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":500,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[],"Elite":0,"Item":[]},
{"Id":6,"Medals":0,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[2341,3],"Elite":0,"Item":[]},
{"Id":7,"Medals":0,"PrizeGeneralId":1072,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[],"Elite":0,"Item":[]},
{"Id":8,"Medals":0,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[2331,3],"Elite":0,"Item":[]},
{"Id":9,"Medals":0,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[2321,3],"Elite":0,"Item":[]},
{"Id":10,"Medals":0,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[2311,3],"Elite":0,"Item":[]},
{"Id":11,"Medals":0,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":50,"PrizeDecoration":0,"GeneralMedal":[],"Elite":0,"Item":[]},
{"Id":12,"Medals":600,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[],"Elite":0,"Item":[]},
{"Id":13,"Medals":0,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[2042,2],"Elite":0,"Item":[]},
{"Id":14,"Medals":0,"PrizeGeneralId":0,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeMerit":0,"PrizeDecoration":0,"GeneralMedal":[],"Elite":0,"Item":[111,30]}
]
