=== e-gleba/world_conqueror_4_ru/patches/enable_all/schemas/WarZoneSetting.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "WarZoneSetting.json",
  "title": "WarZoneSetting",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 1,
        "maximum": 5,
        "enum": [
          1,
          2,
          3,
          4,
          5
        ]
      },
      "Photo": {
        "type": "integer",
        "minimum": 0,
        "maximum": 0,
        "enum": [
          0
        ]
      },
      "X": {
        "type": "integer",
        "minimum": 2070,
        "maximum": 5040,
        "enum": [
          2070,
          2880,
          3422,
          3700,
          5040
        ]
      },
      "Y": {
        "type": "integer",
        "minimum": 270,
        "maximum": 1400,
        "enum": [
          270,
          500,
          800,
          1400
        ]
      },
      "PrizeNum": {
        "type": "array",
        "minItems": 6,
        "maxItems": 6
      },
      "PrizeList": {
        "type": "array",
        "minItems": 6,
        "maxItems": 7
      },
      "CostTicket": {
        "type": "integer",
        "minimum": 2,
        "maximum": 3,
        "enum": [
          2,
          3
        ]
      }
    },
    "required": [
      "Id",
      "Photo",
      "X",
      "Y",
      "PrizeNum",
      "PrizeList",
      "CostTicket"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/WarZoneSetting.json
[
{"Id":1,"Photo":0,"X":2880,"Y":500,"PrizeNum":[1100,1,1400,2,1700,3],"PrizeList":[2011,2031,2051,2121,2141,2241],"CostTicket":2},
{"Id":2,"Photo":0,"X":3422,"Y":1400,"PrizeNum":[1800,1,2400,2,3000,3],"PrizeList":[2021,2041,2111,2131,2231,2241],"CostTicket":2},
{"Id":3,"Photo":0,"X":2070,"Y":270,"PrizeNum":[2500,1,3150,2,3800,4],"PrizeList":[2021,2031,2051,2111,2141,2231,2241],"CostTicket":2},
{"Id":4,"Photo":0,"X":5040,"Y":1400,"PrizeNum":[2850,1,3650,2,4420,4],"PrizeList":[2011,2041,2051,2121,2131,2211,2221],"CostTicket":2},
{"Id":5,"Photo":0,"X":3700,"Y":800,"PrizeNum":[4400,2,6100,4,7700,6],"PrizeList":[2011,2021,2111,2121,2231,2211,2221],"CostTicket":3}
]
