=== e-gleba/world_conqueror_4_ru/patches/extras/schemas/GeneralLevelSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "GeneralLevelSettings.json",
  "title": "GeneralLevelSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 1,
        "maximum": 11,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11
        ]
      },
      "Name": {
        "type": "string",
        "minLength": 2,
        "maxLength": 2,
        "enum": [
          "上将",
          "上尉",
          "上校",
          "中将",
          "中尉",
          "中校",
          "元帅",
          "士官",
          "少将",
          "少尉",
          "少校"
        ]
      },
      "Level": {
        "type": "integer",
        "minimum": 1,
        "maximum": 11,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11
        ]
      },
      "CostMedal": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1000,
        "enum": [
          0,
          40,
          50,
          100,
          150,
          200,
          300,
          400,
          500,
          750,
          1000
        ]
      },
      "NeedHQLv": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1,
        "enum": [
          1
        ]
      },
      "Leadship": {
        "type": "integer",
        "minimum": 3,
        "maximum": 30,
        "enum": [
          3,
          4,
          5,
          7,
          9,
          11,
          14,
          17,
          21,
          25,
          30
        ]
      },
      "HP": {
        "type": "array",
        "minItems": 4,
        "maxItems": 4
      },
      "Score": {
        "type": "integer",
        "minimum": 25,
        "maximum": 1000,
        "enum": [
          25,
          40,
          50,
          100,
          150,
          200,
          300,
          400,
          500,
          750,
          1000
        ]
      }
    },
    "required": [
      "Id",
      "Name",
      "Level",
      "CostMedal",
      "NeedHQLv",
      "Leadship",
      "HP",
      "Score"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/GeneralLevelSettings.json
[
{"Id":1,"Name":"士官","Level":1,"CostMedal":0,"NeedHQLv":1,"Leadship":3,"HP":[12,15,18,21],"Score":25},
{"Id":2,"Name":"少尉","Level":2,"CostMedal":40,"NeedHQLv":1,"Leadship":4,"HP":[16,20,24,28],"Score":40},
{"Id":3,"Name":"中尉","Level":3,"CostMedal":50,"NeedHQLv":1,"Leadship":5,"HP":[20,25,30,35],"Score":50},
{"Id":4,"Name":"上尉","Level":4,"CostMedal":100,"NeedHQLv":1,"Leadship":7,"HP":[24,30,36,42],"Score":100},
{"Id":5,"Name":"少校","Level":5,"CostMedal":150,"NeedHQLv":1,"Leadship":9,"HP":[28,35,42,49],"Score":150},
{"Id":6,"Name":"中校","Level":6,"CostMedal":200,"NeedHQLv":1,"Leadship":11,"HP":[33,41,49,57],"Score":200},
{"Id":7,"Name":"上校","Level":7,"CostMedal":300,"NeedHQLv":1,"Leadship":14,"HP":[38,47,56,65],"Score":300},
{"Id":8,"Name":"少将","Level":8,"CostMedal":400,"NeedHQLv":1,"Leadship":17,"HP":[43,53,63,73],"Score":400},
{"Id":9,"Name":"中将","Level":9,"CostMedal":500,"NeedHQLv":1,"Leadship":21,"HP":[48,59,70,81],"Score":500},
{"Id":10,"Name":"上将","Level":10,"CostMedal":750,"NeedHQLv":1,"Leadship":25,"HP":[54,66,78,90],"Score":750},
{"Id":11,"Name":"元帅","Level":11,"CostMedal":1000,"NeedHQLv":1,"Leadship":30,"HP":[60,75,90,105],"Score":1000}
]
