=== e-gleba/world_conqueror_4_ru/patches/extras/schemas/LegendTacticsSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "LegendTacticsSettings.json",
  "title": "LegendTacticsSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 10101,
        "maximum": 10604
      },
      "Type": {
        "type": "integer",
        "minimum": 1,
        "maximum": 34
      },
      "Effect": {
        "type": "integer",
        "minimum": 0,
        "maximum": 50,
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          10,
          15,
          20,
          30,
          50
        ]
      },
      "SecondEffect": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1651,
        "enum": [
          0,
          58,
          1581,
          1601,
          1651
        ]
      },
      "Distance": {
        "type": "integer",
        "minimum": 0,
        "maximum": 3,
        "enum": [
          0,
          1,
          2,
          3
        ]
      },
      "LimitedArmyType": {
        "type": "integer",
        "minimum": 0,
        "maximum": 101,
        "enum": [
          0,
          1,
          2,
          3,
          101
        ]
      },
      "SynergyArmyType": {
        "type": "integer",
        "minimum": 0,
        "maximum": 102,
        "enum": [
          0,
          1,
          102
        ]
      }
    },
    "required": [
      "Id",
      "Type",
      "Effect",
      "SecondEffect",
      "Distance",
      "LimitedArmyType",
      "SynergyArmyType"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/LegendTacticsSettings.json
[
{"Id":10101,"Type":1,"Effect":3,"SecondEffect":0,"Distance":0,"LimitedArmyType":0,"SynergyArmyType":0},
{"Id":10102,"Type":11,"Effect":2,"SecondEffect":0,"Distance":2,"LimitedArmyType":2,"SynergyArmyType":0},
{"Id":10103,"Type":13,"Effect":0,"SecondEffect":0,"Distance":1,"LimitedArmyType":0,"SynergyArmyType":1},
{"Id":10104,"Type":4,"Effect":10,"SecondEffect":0,"Distance":1,"LimitedArmyType":3,"SynergyArmyType":1},
{"Id":10105,"Type":12,"Effect":1,"SecondEffect":0,"Distance":1,"LimitedArmyType":3,"SynergyArmyType":1},
{"Id":10201,"Type":3,"Effect":10,"SecondEffect":0,"Distance":0,"LimitedArmyType":0,"SynergyArmyType":0},
{"Id":10202,"Type":22,"Effect":20,"SecondEffect":0,"Distance":1,"LimitedArmyType":2,"SynergyArmyType":1},
{"Id":10203,"Type":10,"Effect":2,"SecondEffect":0,"Distance":1,"LimitedArmyType":2,"SynergyArmyType":1},
{"Id":10204,"Type":18,"Effect":2,"SecondEffect":0,"Distance":2,"LimitedArmyType":1,"SynergyArmyType":0},
{"Id":10205,"Type":7,"Effect":15,"SecondEffect":0,"Distance":1,"LimitedArmyType":3,"SynergyArmyType":0},
{"Id":10301,"Type":17,"Effect":10,"SecondEffect":0,"Distance":0,"LimitedArmyType":0,"SynergyArmyType":0},
{"Id":10302,"Type":8,"Effect":0,"SecondEffect":0,"Distance":2,"LimitedArmyType":101,"SynergyArmyType":102},
{"Id":10303,"Type":1,"Effect":2,"SecondEffect":0,"Distance":2,"LimitedArmyType":101,"SynergyArmyType":102},
{"Id":10304,"Type":20,"Effect":4,"SecondEffect":0,"Distance":2,"LimitedArmyType":3,"SynergyArmyType":0},
{"Id":10305,"Type":6,"Effect":1,"SecondEffect":0,"Distance":1,"LimitedArmyType":1,"SynergyArmyType":0},
{"Id":10306,"Type":21,"Effect":15,"SecondEffect":0,"Distance":1,"LimitedArmyType":1,"SynergyArmyType":0},
{"Id":10401,"Type":23,"Effect":2,"SecondEffect":0,"Distance":0,"LimitedArmyType":0,"SynergyArmyType":0},
{"Id":10402,"Type":24,"Effect":2,"SecondEffect":1581,"Distance":0,"LimitedArmyType":3,"SynergyArmyType":0},
{"Id":10403,"Type":25,"Effect":2,"SecondEffect":58,"Distance":0,"LimitedArmyType":2,"SynergyArmyType":0},
{"Id":10404,"Type":26,"Effect":50,"SecondEffect":0,"Distance":1,"LimitedArmyType":2,"SynergyArmyType":1},
{"Id":10405,"Type":26,"Effect":50,"SecondEffect":0,"Distance":1,"LimitedArmyType":3,"SynergyArmyType":1},
{"Id":10501,"Type":27,"Effect":2,"SecondEffect":1601,"Distance":2,"LimitedArmyType":0,"SynergyArmyType":0},
{"Id":10502,"Type":28,"Effect":0,"SecondEffect":0,"Distance":2,"LimitedArmyType":2,"SynergyArmyType":0},
{"Id":10503,"Type":29,"Effect":10,"SecondEffect":0,"Distance":0,"LimitedArmyType":3,"SynergyArmyType":0},
{"Id":10504,"Type":30,"Effect":5,"SecondEffect":0,"Distance":2,"LimitedArmyType":1,"SynergyArmyType":0},
{"Id":10601,"Type":31,"Effect":0,"SecondEffect":1651,"Distance":0,"LimitedArmyType":0,"SynergyArmyType":0},
{"Id":10602,"Type":32,"Effect":20,"SecondEffect":0,"Distance":3,"LimitedArmyType":0,"SynergyArmyType":0},
{"Id":10603,"Type":33,"Effect":6,"SecondEffect":0,"Distance":2,"LimitedArmyType":1,"SynergyArmyType":0},
{"Id":10604,"Type":34,"Effect":30,"SecondEffect":0,"Distance":2,"LimitedArmyType":3,"SynergyArmyType":1}
]
