=== e-gleba/world_conqueror_4_ru/patches/extras/schemas/ScenarioSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "ScenarioSettings.json",
  "title": "ScenarioSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 0,
        "maximum": 5,
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5
        ]
      },
      "UnlockRequirements": {
        "type": "array",
        "minItems": 0,
        "maxItems": 2
      },
      "UnlockedConquerId": {
        "type": "integer",
        "minimum": 0,
        "maximum": 4,
        "enum": [
          0,
          1,
          2,
          3,
          4
        ]
      },
      "GeneralId": {
        "type": "array",
        "minItems": 0,
        "maxItems": 2
      },
      "DialoguesID": {
        "type": "array",
        "minItems": 0,
        "maxItems": 6
      },
      "Open": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1,
        "enum": [
          0,
          1
        ]
      },
      "Visible": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1,
        "enum": [
          0,
          1
        ]
      }
    },
    "required": [
      "Id",
      "UnlockRequirements",
      "UnlockedConquerId",
      "GeneralId",
      "DialoguesID",
      "Open",
      "Visible"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/ScenarioSettings.json
[
{"Id":0,"UnlockRequirements":[],"UnlockedConquerId":0,"GeneralId":[1031],"DialoguesID":[1,2,3],"Open":1,"Visible":1},
{"Id":1,"UnlockRequirements":[],"UnlockedConquerId":1,"GeneralId":[1050,1031],"DialoguesID":[4,5],"Open":1,"Visible":1},
{"Id":2,"UnlockRequirements":[10111,10211],"UnlockedConquerId":2,"GeneralId":[1027,1031],"DialoguesID":[6,7],"Open":1,"Visible":1},
{"Id":3,"UnlockRequirements":[10309,10409],"UnlockedConquerId":3,"GeneralId":[1018,1031],"DialoguesID":[8,9],"Open":1,"Visible":1},
{"Id":4,"UnlockRequirements":[10506,10606],"UnlockedConquerId":4,"GeneralId":[1031],"DialoguesID":[10,11,12,13,14,15],"Open":1,"Visible":1},
{"Id":5,"UnlockRequirements":[],"UnlockedConquerId":0,"GeneralId":[],"DialoguesID":[],"Open":0,"Visible":0}
]
