=== e-gleba/world_conqueror_4_ru/schemas/AchievementSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "AchievementSettings.json",
  "title": "AchievementSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 101,
        "maximum": 4105
      },
      "UnlockId": {
        "type": "integer",
        "minimum": 0,
        "maximum": 4105
      },
      "InitVisible": {
        "type": "boolean"
      },
      "Type": {
        "type": "integer",
        "minimum": 0,
        "maximum": 41
      },
      "Parameter": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100109,
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5,
          10307,
          20307,
          30507,
          40409,
          50407,
          60308,
          70407,
          80407,
          90305,
          100109
        ]
      },
      "Parameter2": {
        "type": "integer",
        "minimum": 0,
        "maximum": 6,
        "enum": [
          0,
          1,
          2,
          3,
          5,
          6
        ]
      },
      "Num": {
        "type": "integer",
        "minimum": 1,
        "maximum": 8600
      },
      "PrizeMedals": {
        "type": "integer",
        "minimum": 0,
        "maximum": 500,
        "enum": [
          0,
          25,
          50,
          100,
          150,
          300,
          350,
          500
        ]
      },
      "PrizeDecoration": {
        "type": "integer",
        "minimum": 0,
        "maximum": 2121,
        "enum": [
          0,
          1001,
          1002,
          1003,
          1004,
          1005,
          1006,
          1007,
          1008,
          1009,
          1010,
          1011,
          1012,
          1013,
          1014,
          1015,
          1016,
          2011,
          2021,
          2031,
          2111,
          2121
        ]
      },
      "Pic": {
        "type": [
          "null",
          "null"
        ]
      },
      "PrizeMerit": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100,
        "enum": [
          0,
          60,
          75,
          100
        ]
      },
      "PrizePoint": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15,
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          15
        ]
      },
      "Item": {
        "type": "array",
        "minItems": 0,
        "maxItems": 2
      },
      "PriorityTag": {
        "type": "integer",
        "minimum": 0,
        "maximum": 5,
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5
        ]
      }
    },
    "required": [
      "Id",
      "UnlockId",
      "InitVisible",
      "Type",
      "Parameter",
      "Parameter2",
      "Num",
      "PrizeMedals",
      "PrizeDecoration",
      "PrizeMerit",
      "PrizePoint",
      "Item",
      "PriorityTag"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/diff_mod/assets/data/AchievementSettings.json
[
  {
    "Id": 101,
    "UnlockId": 0,
    "InitVisible": true,
    "Type": 0,
    "Parameter": 1,
    "Parameter2": 0,
    "Num": 22,
    "PrizeMedals": 300,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 3
  },
  {
    "Id": 102,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 0,
    "Parameter": 2,
    "Parameter2": 0,
    "Num": 18,
    "PrizeMedals": 300,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 3
  },
  {
    "Id": 103,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 0,
    "Parameter": 3,
    "Parameter2": 0,
    "Num": 12,
    "PrizeMedals": 300,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 3
  },
  {
    "Id": 104,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 0,
    "Parameter": 4,
    "Parameter2": 0,
    "Num": 9,
    "PrizeMedals": 300,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 3
  },
  {
    "Id": 111,
    "UnlockId": 0,
    "InitVisible": true,
    "Type": 10,
    "Parameter": 1,
    "Parameter2": 0,
    "Num": 22,
    "PrizeMedals": 350,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 112,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 10,
    "Parameter": 2,
    "Parameter2": 0,
    "Num": 18,
    "PrizeMedals": 350,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 113,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 10,
    "Parameter": 3,
    "Parameter2": 0,
    "Num": 12,
    "PrizeMedals": 350,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 114,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 10,
    "Parameter": 4,
    "Parameter2": 0,
    "Num": 9,
    "PrizeMedals": 350,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 201,
    "UnlockId": 0,
    "InitVisible": true,
    "Type": 1,
    "Parameter": 1,
    "Parameter2": 3,
    "Num": 1,
    "PrizeMedals": 50,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 202,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 1,
    "Parameter": 2,
    "Parameter2": 3,
    "Num": 1,
    "PrizeMedals": 50,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 203,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 1,
    "Parameter": 3,
    "Parameter2": 3,
    "Num": 1,
    "PrizeMedals": 50,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 204,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 1,
    "Parameter": 4,
    "Parameter2": 3,
    "Num": 1,
    "PrizeMedals": 50,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 301,
    "UnlockId": 0,
    "InitVisible": true,
    "Type": 2,
    "Parameter": 1,
    "Parameter2": 2,
    "Num": 1,
    "PrizeMedals": 100,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 302,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 2,
    "Parameter": 2,
    "Parameter2": 2,
    "Num": 1,
    "PrizeMedals": 100,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 303,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 2,
    "Parameter": 3,
    "Parameter2": 2,
    "Num": 1,
    "PrizeMedals": 100,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 304,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 2,
    "Parameter": 4,
    "Parameter2": 2,
    "Num": 1,
    "PrizeMedals": 100,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 401,
    "UnlockId": 0,
    "InitVisible": true,
    "Type": 3,
    "Parameter": 1,
    "Parameter2": 1,
    "Num": 1,
    "PrizeMedals": 150,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 402,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 3,
    "Parameter": 2,
    "Parameter2": 1,
    "Num": 1,
    "PrizeMedals": 150,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 403,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 3,
    "Parameter": 3,
    "Parameter2": 1,
    "Num": 1,
    "PrizeMedals": 150,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 404,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 3,
    "Parameter": 4,
    "Parameter2": 1,
    "Num": 1,
    "PrizeMedals": 150,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 501,
    "UnlockId": 0,
    "InitVisible": true,
    "Type": 4,
    "Parameter": 1,
    "Parameter2": 5,
    "Num": 1,
    "PrizeMedals": 500,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 502,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 4,
    "Parameter": 2,
    "Parameter2": 5,
    "Num": 1,
    "PrizeMedals": 500,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 503,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 4,
    "Parameter": 3,
    "Parameter2": 5,
    "Num": 1,
    "PrizeMedals": 500,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 504,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 4,
    "Parameter": 4,
    "Parameter2": 5,
    "Num": 1,
    "PrizeMedals": 500,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 601,
    "UnlockId": 0,
    "InitVisible": true,
    "Type": 5,
    "Parameter": 1,
    "Parameter2": 6,
    "Num": 1,
    "PrizeMedals": 0,
    "PrizeDecoration": 1013,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 602,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 5,
    "Parameter": 2,
    "Parameter2": 6,
    "Num": 1,
    "PrizeMedals": 0,
    "PrizeDecoration": 1014,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 603,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 5,
    "Parameter": 3,
    "Parameter2": 6,
    "Num": 1,
    "PrizeMedals": 0,
    "PrizeDecoration": 1015,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 604,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 5,
    "Parameter": 4,
    "Parameter2": 6,
    "Num": 1,
    "PrizeMedals": 0,
    "PrizeDecoration": 1016,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 701,
    "UnlockId": 0,
    "InitVisible": true,
    "Type": 6,
    "Parameter": 0,
    "Parameter2": 0,
    "Num": 5,
    "PrizeMedals": 25,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 5
  },
  {
    "Id": 702,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 6,
    "Parameter": 0,
    "Parameter2": 0,
    "Num": 10,
    "PrizeMedals": 25,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 5
  },
  {
    "Id": 703,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 6,
    "Parameter": 0,
    "Parameter2": 0,
    "Num": 15,
    "PrizeMedals": 25,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 5
  },
  {
    "Id": 704,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 6,
    "Parameter": 0,
    "Parameter2": 0,
    "Num": 20,
    "PrizeMedals": 25,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 5
  },
  {
    "Id": 705,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 6,
    "Parameter": 0,
    "Parameter2": 0,
    "Num": 30,
    "PrizeMedals": 25,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 5
  },
  {
    "Id": 801,
    "UnlockId": 0,
    "InitVisible": true,
    "Type": 7,
    "Parameter": 0,
    "Parameter2": 0,
    "Num": 4,
    "PrizeMedals": 25,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 802,
    "UnlockId": 0,
    "InitVisible": false,
    "Type": 7,
    "Parameter": 0,
    "Parameter2": 0,
    "Num": 8,
    "PrizeMedals": 25,
    "PrizeDecoration": 0,
    "Pic": null,
    "PrizeMerit": 0,
    "PrizePoint": 0,
    "Item": [],
    "PriorityTag": 0
  },
  {
    "Id": 803,
