=== e-gleba/world_conqueror_4_ru/schemas/ArmyLevelSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "ArmyLevelSettings.json",
  "title": "ArmyLevelSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Level": {
        "type": "integer",
        "minimum": -1,
        "maximum": 6,
        "enum": [
          -1,
          1,
          2,
          3,
          4,
          5,
          6
        ]
      },
      "AddHP": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100,
        "enum": [
          0,
          20,
          40,
          60,
          80,
          100
        ]
      },
      "AddAttack": {
        "type": "integer",
        "minimum": 0,
        "maximum": 20,
        "enum": [
          0,
          4,
          8,
          12,
          16,
          20
        ]
      },
      "AddDefense": {
        "type": "integer",
        "minimum": 0,
        "maximum": 10,
        "enum": [
          0,
          2,
          4,
          6,
          8,
          10
        ]
      },
      "NeedExp": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1600,
        "enum": [
          0,
          250,
          450,
          800,
          1200,
          1600
        ]
      }
    },
    "required": [
      "Level",
      "AddHP",
      "AddAttack",
      "AddDefense",
      "NeedExp"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/ArmyLevelSettings.json
[
{"Level":1,"AddHP":0,"AddAttack":0,"AddDefense":0,"NeedExp":250},
{"Level":2,"AddHP":20,"AddAttack":4,"AddDefense":2,"NeedExp":450},
{"Level":3,"AddHP":40,"AddAttack":8,"AddDefense":4,"NeedExp":800},
{"Level":4,"AddHP":60,"AddAttack":12,"AddDefense":6,"NeedExp":1200},
{"Level":5,"AddHP":80,"AddAttack":16,"AddDefense":8,"NeedExp":1600},
{"Level":6,"AddHP":100,"AddAttack":20,"AddDefense":10,"NeedExp":0},
{"Level":-1,"AddHP":0,"AddAttack":0,"AddDefense":0,"NeedExp":0}
]
