=== e-gleba/world_conqueror_4_ru/schemas/ArmyGroupChallengeSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "ArmyGroupChallengeSettings.json",
  "title": "ArmyGroupChallengeSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 1001,
        "maximum": 6601
      },
      "UnlockId": {
        "type": "integer",
        "minimum": 0,
        "maximum": 6405
      },
      "Level": {
        "type": "integer",
        "minimum": 1,
        "maximum": 5,
        "enum": [
          1,
          2,
          3,
          4,
          5
        ]
      },
      "Type": {
        "type": "integer",
        "minimum": 0,
        "maximum": 15,
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15
        ]
      },
      "EventId": {
        "type": "integer",
        "minimum": 801,
        "maximum": 806,
        "enum": [
          801,
          802,
          803,
          804,
          805,
          806
        ]
      },
      "Parameter": {
        "type": "integer",
        "minimum": 1,
        "maximum": 65,
        "enum": [
          1,
          2,
          3,
          4,
          6,
          8,
          10,
          12,
          15,
          20,
          25,
          30,
          35,
          40,
          45,
          50,
          55,
          60,
          65
        ]
      },
      "Parameters": {
        "type": "array",
        "minItems": 0,
        "maxItems": 4
      },
      "PrizePoint": {
        "type": "integer",
        "minimum": 2,
        "maximum": 16,
        "enum": [
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          12,
          15,
          16
        ]
      }
    },
    "required": [
      "Id",
      "UnlockId",
      "Level",
      "Type",
      "EventId",
      "Parameter",
      "Parameters",
      "PrizePoint"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/diff_mod/assets/data/ArmyGroupChallengeSettings.json
[
  {
    "Id": 1001,
    "UnlockId": 0,
    "Level": 1,
    "Type": 0,
    "EventId": 801,
    "Parameter": 1,
    "Parameters": [],
    "PrizePoint": 8
  },
  {
    "Id": 1002,
    "UnlockId": 0,
    "Level": 1,
    "Type": 1,
    "EventId": 801,
    "Parameter": 2,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 1003,
    "UnlockId": 0,
    "Level": 1,
    "Type": 2,
    "EventId": 801,
    "Parameter": 3,
    "Parameters": [],
    "PrizePoint": 4
  },
  {
    "Id": 1101,
    "UnlockId": 0,
    "Level": 1,
    "Type": 3,
    "EventId": 801,
    "Parameter": 4,
    "Parameters": [],
    "PrizePoint": 4
  },
  {
    "Id": 1102,
    "UnlockId": 0,
    "Level": 1,
    "Type": 4,
    "EventId": 801,
    "Parameter": 3,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 1103,
    "UnlockId": 0,
    "Level": 1,
    "Type": 5,
    "EventId": 801,
    "Parameter": 2,
    "Parameters": [],
    "PrizePoint": 8
  },
  {
    "Id": 1201,
    "UnlockId": 0,
    "Level": 1,
    "Type": 7,
    "EventId": 801,
    "Parameter": 2,
    "Parameters": [
      106,
      107
    ],
    "PrizePoint": 10
  },
  {
    "Id": 1301,
    "UnlockId": 0,
    "Level": 1,
    "Type": 8,
    "EventId": 801,
    "Parameter": 2,
    "Parameters": [
      118,
      119
    ],
    "PrizePoint": 10
  },
  {
    "Id": 1401,
    "UnlockId": 0,
    "Level": 1,
    "Type": 9,
    "EventId": 801,
    "Parameter": 25,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 1402,
    "UnlockId": 0,
    "Level": 2,
    "Type": 9,
    "EventId": 801,
    "Parameter": 35,
    "Parameters": [],
    "PrizePoint": 7
  },
  {
    "Id": 1403,
    "UnlockId": 0,
    "Level": 3,
    "Type": 9,
    "EventId": 801,
    "Parameter": 45,
    "Parameters": [],
    "PrizePoint": 8
  },
  {
    "Id": 1404,
    "UnlockId": 0,
    "Level": 4,
    "Type": 9,
    "EventId": 801,
    "Parameter": 55,
    "Parameters": [],
    "PrizePoint": 9
  },
  {
    "Id": 1501,
    "UnlockId": 0,
    "Level": 1,
    "Type": 10,
    "EventId": 801,
    "Parameter": 40,
    "Parameters": [
      104
    ],
    "PrizePoint": 2
  },
  {
    "Id": 1502,
    "UnlockId": 0,
    "Level": 2,
    "Type": 10,
    "EventId": 801,
    "Parameter": 25,
    "Parameters": [
      104
    ],
    "PrizePoint": 3
  },
  {
    "Id": 1601,
    "UnlockId": 0,
    "Level": 1,
    "Type": 11,
    "EventId": 801,
    "Parameter": 40,
    "Parameters": [
      115
    ],
    "PrizePoint": 2
  },
  {
    "Id": 1602,
    "UnlockId": 0,
    "Level": 2,
    "Type": 11,
    "EventId": 801,
    "Parameter": 25,
    "Parameters": [
      115
    ],
    "PrizePoint": 3
  },
  {
    "Id": 1701,
    "UnlockId": 0,
    "Level": 1,
    "Type": 12,
    "EventId": 801,
    "Parameter": 45,
    "Parameters": [
      110
    ],
    "PrizePoint": 2
  },
  {
    "Id": 1702,
    "UnlockId": 0,
    "Level": 2,
    "Type": 12,
    "EventId": 801,
    "Parameter": 35,
    "Parameters": [
      110
    ],
    "PrizePoint": 3
  },
  {
    "Id": 1801,
    "UnlockId": 0,
    "Level": 1,
    "Type": 13,
    "EventId": 801,
    "Parameter": 40,
    "Parameters": [
      113
    ],
    "PrizePoint": 2
  },
  {
    "Id": 1802,
    "UnlockId": 0,
    "Level": 2,
    "Type": 13,
    "EventId": 801,
    "Parameter": 25,
    "Parameters": [
      113
    ],
    "PrizePoint": 3
  },
  {
    "Id": 2001,
    "UnlockId": 0,
    "Level": 1,
    "Type": 0,
    "EventId": 802,
    "Parameter": 1,
    "Parameters": [],
    "PrizePoint": 8
  },
  {
    "Id": 2002,
    "UnlockId": 0,
    "Level": 1,
    "Type": 1,
    "EventId": 802,
    "Parameter": 2,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 2003,
    "UnlockId": 0,
    "Level": 1,
    "Type": 2,
    "EventId": 802,
    "Parameter": 3,
    "Parameters": [],
    "PrizePoint": 4
  },
  {
    "Id": 2101,
    "UnlockId": 0,
    "Level": 1,
    "Type": 3,
    "EventId": 802,
    "Parameter": 4,
    "Parameters": [],
    "PrizePoint": 4
  },
  {
    "Id": 2102,
    "UnlockId": 0,
    "Level": 1,
    "Type": 4,
    "EventId": 802,
    "Parameter": 3,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 2103,
    "UnlockId": 0,
    "Level": 1,
    "Type": 5,
    "EventId": 802,
    "Parameter": 2,
    "Parameters": [],
    "PrizePoint": 8
  },
  {
    "Id": 2201,
    "UnlockId": 0,
    "Level": 1,
    "Type": 7,
    "EventId": 802,
    "Parameter": 3,
    "Parameters": [
      206,
      207,
      208
    ],
    "PrizePoint": 10
  },
  {
    "Id": 2301,
    "UnlockId": 0,
    "Level": 1,
    "Type": 8,
    "EventId": 802,
    "Parameter": 2,
    "Parameters": [
      213,
      214
    ],
    "PrizePoint": 10
  },
  {
    "Id": 2401,
    "UnlockId": 0,
    "Level": 1,
    "Type": 9,
    "EventId": 802,
    "Parameter": 25,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 2402,
    "UnlockId": 0,
    "Level": 2,
    "Type": 9,
    "EventId": 802,
    "Parameter": 35,
    "Parameters": [],
    "PrizePoint": 7
  },
  {
    "Id": 2403,
    "UnlockId": 0,
    "Level": 3,
    "Type": 9,
    "EventId": 802,
    "Parameter": 45,
    "Parameters": [],
    "PrizePoint": 8
  },
  {
    "Id": 2404,
    "UnlockId": 0,
    "Level": 4,
    "Type": 9,
    "EventId": 802,
    "Parameter": 55,
    "Parameters": [],
    "PrizePoint": 9
  },
  {
    "Id": 2501,
    "UnlockId": 0,
    "Level": 1,
    "Type": 10,
    "EventId": 802,
    "Parameter": 45,
    "Parameters": [
      202
    ],
    "PrizePoint": 2
  },
  {
    "Id": 2502,
    "UnlockId": 0,
    "Level": 2,
    "Type": 10,
    "EventId": 802,
    "Parameter": 25,
    "Parameters": [
      202
    ],
    "PrizePoint": 3
  },
  {
    "Id": 2601,
    "UnlockId": 0,
    "Level": 1,
    "Type": 11,
    "EventId": 802,
    "Parameter": 45,
    "Parameters": [
      221
    ],
    "PrizePoint": 2
  },
  {
    "Id": 2602,
    "UnlockId": 0,
    "Level": 2,
    "Type": 11,
    "EventId": 802,
    "Parameter": 25,
    "Parameters": [
      221
    ],
    "PrizePoint": 3
  },
  {
    "Id": 2701,
    "UnlockId": 0,
    "Level": 1,
    "Type": 12,
    "EventId": 802,
    "Parameter": 50,
    "Parameters": [
      209
    ],
    "PrizePoint": 2
  },
  {
    "Id": 2702,
    "UnlockId": 0,
    "Level": 2,
    "Type": 12,
    "EventId": 802,
    "Parameter": 35,
    "Parameters": [
      209
    ],
    "PrizePoint": 3
  },
  {
    "Id": 2801,
    "UnlockId": 0,
    "Level": 1,
    "Type": 13,
    "EventId": 802,
    "Parameter": 45,
    "Parameters": [
      223
    ],
    "PrizePoint": 2
  },
  {
    "Id": 2802,
    "UnlockId": 0,
    "Level": 2,
    "Type": 13,
    "EventId": 802,
    "Parameter": 30,
    "Parameters": [
      223
    ],
    "PrizePoint": 3
  },
  {
    "Id": 3001,
    "UnlockId": 0,
    "Level": 1,
    "Type": 0,
    "EventId": 803,
    "Parameter": 1,
    "Parameters": [],
    "PrizePoint": 8
  },
  {
    "Id": 3002,
    "UnlockId": 0,
    "Level": 1,
    "Type": 1,
    "EventId": 803,
    "Parameter": 2,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 3003,
    "UnlockId": 0,
    "Level": 1,
    "Type": 2,
    "EventId": 803,
    "Parameter": 3,
    "Parameters": [],
    "PrizePoint": 4
  },
  {
    "Id": 3101,
    "UnlockId": 0,
    "Level": 1,
    "Type": 3,
    "EventId": 803,
    "Parameter": 4,
    "Parameters": [],
    "PrizePoint": 4
  },
  {
    "Id": 3102,
    "UnlockId": 0,
    "Level": 1,
    "Type": 4,
    "EventId": 803,
    "Parameter": 3,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 3103,
    "UnlockId": 0,
    "Level": 1,
    "Type": 5,
    "EventId": 803,
    "Parameter": 2,
    "Parameters": [],
    "PrizePoint": 8
  },
  {
    "Id": 3201,
    "UnlockId": 0,
    "Level": 1,
    "Type": 7,
    "EventId": 803,
    "Parameter": 2,
    "Parameters": [
      314,
      315
    ],
    "PrizePoint": 16
  },
  {
    "Id": 3401,
    "UnlockId": 0,
    "Level": 1,
    "Type": 9,
    "EventId": 803,
    "Parameter": 25,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 3402,
    "UnlockId": 0,
    "Level": 2,
    "Type": 9,
    "EventId": 803,
    "Parameter": 35,
    "Parameters": [],
    "PrizePoint": 7
  },
  {
    "Id": 3403,
    "UnlockId": 0,
    "Level": 3,
    "Type": 9,
    "EventId": 803,
    "Parameter": 45,
    "Parameters": [],
    "PrizePoint": 8
  },
  {
    "Id": 3404,
    "UnlockId": 0,
    "Level": 4,
    "Type": 9,
    "EventId": 803,
    "Parameter": 55,
    "Parameters": [],
    "PrizePoint": 10
  },
  {
    "Id": 3405,
    "UnlockId": 0,
    "Level": 5,
    "Type": 9,
    "EventId": 803,
    "Parameter": 65,
    "Parameters": [],
    "PrizePoint": 12
  },
  {
    "Id": 3501,
    "UnlockId": 0,
    "Level": 1,
    "Type": 14,
    "EventId": 803,
    "Parameter": 10,
    "Parameters": [
      16,
      4908
    ],
    "PrizePoint": 8
  },
  {
    "Id": 3601,
    "UnlockId": 0,
    "Level": 1,
    "Type": 15,
    "EventId": 803,
    "Parameter": 15,
    "Parameters": [
      19,
      10712
    ],
    "PrizePoint": 8
  },
  {
    "Id": 5001,
    "UnlockId": 0,
    "Level": 1,
    "Type": 0,
    "EventId": 805,
    "Parameter": 1,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 5002,
    "UnlockId": 0,
    "Level": 1,
    "Type": 1,
    "EventId": 805,
    "Parameter": 2,
    "Parameters": [],
    "PrizePoint": 5
  },
  {
    "Id": 5003,
    "UnlockId": 0,
    "Level": 1,
    "Type": 2,
    "EventId": 805,
    "Parameter": 3,
    "Parameters": [],
    "PrizePoint": 4
  },
  {
    "Id": 5101,
    "UnlockId": 0,
    "Level": 1,
    "Type": 3,
    "EventId": 805,
    "Parameter": 4,
    "Parameters": [],
    "PrizePoint": 4
  },
  {
    "Id": 5102,
    "UnlockId": 0,
    "Level": 1,
    "Type": 4,
    "EventId": 805,
    "Parameter": 3,
    "Parameters": [],
    "PrizePoint": 6
  },
  {
    "Id": 5103,
    "UnlockId": 0,
    "Level": 1,
    "Type": 5,
    "EventId": 805,
    "Parameter": 2,
    "Parameters": [],
    "PrizePoint": 8
  },
  {
    "Id": 5201,
    "UnlockId": 0,
    "Level": 1,
    "Type": 7,
