=== e-gleba/world_conqueror_4_ru/schemas/ConquerPassSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "ConquerPassSettings.json",
  "title": "ConquerPassSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 1,
        "maximum": 63
      },
      "Point": {
        "type": "integer",
        "minimum": 1,
        "maximum": 310
      },
      "Medals": {
        "type": "integer",
        "minimum": 0,
        "maximum": 950,
        "enum": [
          0,
          150,
          200,
          250,
          300,
          350,
          500,
          650,
          800,
          950
        ]
      },
      "GeneralMedal": {
        "type": "array",
        "minItems": 0,
        "maxItems": 2
      },
      "GeneralId": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1109,
        "enum": [
          0,
          1084,
          1086,
          1090,
          1109
        ]
      },
      "Item": {
        "type": [
          "array",
          "null"
        ],
        "minItems": 2,
        "maxItems": 2
      },
      "UnlockSkillID": {
        "type": "integer",
        "minimum": 0,
        "maximum": 3311,
        "enum": [
          0,
          3311
        ]
      },
      "Sword": {
        "type": "integer",
        "minimum": 0,
        "maximum": 12,
        "enum": [
          0,
          8,
          12
        ]
      },
      "Sceptre": {
        "type": "integer",
        "minimum": 0,
        "maximum": 2,
        "enum": [
          0,
          2
        ]
      }
    },
    "required": [
      "Id",
      "Point",
      "Medals",
      "GeneralMedal",
      "GeneralId",
      "UnlockSkillID",
      "Sword",
      "Sceptre"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/ConquerPassSettings.json
[
{"Id":1,"Point":1,"Medals":150,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":2,"Point":2,"Medals":0,"GeneralMedal":[2042,2],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":3,"Point":4,"Medals":150,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":4,"Point":6,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[114,10],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":5,"Point":9,"Medals":0,"GeneralMedal":[1014,1],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":6,"Point":12,"Medals":200,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":7,"Point":16,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[118,10],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":8,"Point":20,"Medals":200,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":9,"Point":24,"Medals":0,"GeneralMedal":[],"GeneralId":1084,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":10,"Point":30,"Medals":0,"GeneralMedal":[1016,1],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":11,"Point":36,"Medals":0,"GeneralMedal":[2022,2],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":12,"Point":42,"Medals":250,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":13,"Point":50,"Medals":0,"GeneralMedal":[2012,2],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":14,"Point":60,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[120,10],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":15,"Point":70,"Medals":0,"GeneralMedal":[],"GeneralId":1086,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":16,"Point":75,"Medals":250,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":17,"Point":80,"Medals":0,"GeneralMedal":[2242,2],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":18,"Point":85,"Medals":250,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":19,"Point":90,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[115,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":20,"Point":95,"Medals":0,"GeneralMedal":[2232,2],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":21,"Point":100,"Medals":300,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":22,"Point":105,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[119,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":23,"Point":110,"Medals":300,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":24,"Point":115,"Medals":0,"GeneralMedal":[2222,2],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":25,"Point":120,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[122,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":26,"Point":125,"Medals":350,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":27,"Point":130,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[108,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":28,"Point":135,"Medals":350,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":29,"Point":140,"Medals":0,"GeneralMedal":[2212,2],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":30,"Point":145,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[117,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":31,"Point":150,"Medals":0,"GeneralMedal":[],"GeneralId":1090,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":32,"Point":155,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":3311,"Sword":0,"Sceptre":0},
{"Id":33,"Point":160,"Medals":0,"GeneralMedal":[2052,4],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":34,"Point":165,"Medals":500,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":35,"Point":170,"Medals":0,"GeneralMedal":[2022,4],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":36,"Point":175,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[126,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":37,"Point":180,"Medals":500,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":38,"Point":185,"Medals":0,"GeneralMedal":[2012,4],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":39,"Point":190,"Medals":500,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":40,"Point":195,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[125,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":41,"Point":200,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":8,"Sceptre":0},
{"Id":42,"Point":205,"Medals":650,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":43,"Point":210,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[129,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":44,"Point":215,"Medals":0,"GeneralMedal":[2212,4],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":45,"Point":220,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":12,"Sceptre":0},
{"Id":46,"Point":225,"Medals":0,"GeneralMedal":[1019,1],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":47,"Point":230,"Medals":650,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":48,"Point":235,"Medals":0,"GeneralMedal":[1020,1],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":49,"Point":240,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[133,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":50,"Point":245,"Medals":800,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":51,"Point":250,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[134,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":52,"Point":255,"Medals":0,"GeneralMedal":[1017,1],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":53,"Point":260,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[131,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":54,"Point":265,"Medals":800,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":55,"Point":270,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[128,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":56,"Point":275,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":2},
{"Id":57,"Point":280,"Medals":800,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":58,"Point":285,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[132,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":59,"Point":290,"Medals":0,"GeneralMedal":[1018,1],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":60,"Point":295,"Medals":950,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":61,"Point":300,"Medals":0,"GeneralMedal":[],"GeneralId":1109,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":62,"Point":305,"Medals":950,"GeneralMedal":[],"GeneralId":0,"Item":null,"UnlockSkillID":0,"Sword":0,"Sceptre":0},
{"Id":63,"Point":310,"Medals":0,"GeneralMedal":[],"GeneralId":0,"Item":[139,15],"UnlockSkillID":0,"Sword":0,"Sceptre":0}
]
