=== e-gleba/world_conqueror_4_ru/schemas/ConquerPrizeSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "ConquerPrizeSettings.json",
  "title": "ConquerPrizeSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 1,
        "maximum": 6,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6
        ]
      },
      "Min": {
        "type": "integer",
        "minimum": 1,
        "maximum": 135001,
        "enum": [
          1,
          70001,
          80001,
          90001,
          110001,
          135001
        ]
      },
      "Max": {
        "type": "integer",
        "minimum": 70000,
        "maximum": 999999,
        "enum": [
          70000,
          80000,
          90000,
          110000,
          135000,
          999999
        ]
      },
      "ChallengeMin": {
        "type": "integer",
        "minimum": 1,
        "maximum": 210001,
        "enum": [
          1,
          70001,
          90001,
          110001,
          160001,
          210001
        ]
      },
      "ChallengeMax": {
        "type": "integer",
        "minimum": 70000,
        "maximum": 999999,
        "enum": [
          70000,
          90000,
          110000,
          160000,
          210000,
          999999
        ]
      },
      "Override": {
        "type": "number",
        "minimum": 0.65,
        "maximum": 2.0,
        "enum": [
          0.65,
          0.75,
          0.85,
          1.0,
          1.5,
          2.0
        ]
      }
    },
    "required": [
      "Id",
      "Min",
      "Max",
      "ChallengeMin",
      "ChallengeMax",
      "Override"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/ConquerPrizeSettings.json
[
{"Id":1,"Min":1,"Max":70000,"ChallengeMin":1,"ChallengeMax":70000,"Override":0.65},
{"Id":2,"Min":70001,"Max":80000,"ChallengeMin":70001,"ChallengeMax":90000,"Override":0.75},
{"Id":3,"Min":80001,"Max":90000,"ChallengeMin":90001,"ChallengeMax":110000,"Override":0.85},
{"Id":4,"Min":90001,"Max":110000,"ChallengeMin":110001,"ChallengeMax":160000,"Override":1.0},
{"Id":5,"Min":110001,"Max":135000,"ChallengeMin":160001,"ChallengeMax":210000,"Override":1.5},
{"Id":6,"Min":135001,"Max":999999,"ChallengeMin":210001,"ChallengeMax":999999,"Override":2.0}
]
