=== e-gleba/world_conqueror_4_ru/schemas/FrontierStageSetting.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "FrontierStageSetting.json",
  "title": "FrontierStageSetting",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 10101,
        "maximum": 100109
      },
      "UnlockedStageids": {
        "type": "array",
        "minItems": 0,
        "maxItems": 1
      },
      "UnlockedNodes": {
        "type": "array",
        "minItems": 0,
        "maxItems": 2
      },
      "Camp": {
        "type": "integer",
        "minimum": 1,
        "maximum": 6,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6
        ]
      },
      "Seat": {
        "type": "integer",
        "minimum": 4,
        "maximum": 12,
        "enum": [
          4,
          6,
          8,
          10,
          12
        ]
      },
      "Node": {
        "type": "integer",
        "minimum": 101,
        "maximum": 1001
      },
      "Difficulty": {
        "type": "integer",
        "minimum": 1,
        "maximum": 16,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16
        ]
      },
      "General": {
        "type": "integer",
        "minimum": 20013,
        "maximum": 29142
      },
      "PrizeMerit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "enum": [
          1,
          2,
          5,
          10
        ]
      },
      "PrizeGold": {
        "type": "integer",
        "minimum": 0,
        "maximum": 21000,
        "enum": [
          0,
          1500,
          4500,
          12000,
          21000
        ]
      },
      "PrizeIndustry": {
        "type": "integer",
        "minimum": 0,
        "maximum": 3000,
        "enum": [
          0,
          450,
          900,
          1800,
          3000
        ]
      },
      "PrizeEnergy": {
        "type": "integer",
        "minimum": 0,
        "maximum": 750,
        "enum": [
          0,
          90,
          240,
          480,
          750
        ]
      },
      "PrizeTech": {
        "type": "integer",
        "minimum": 0,
        "maximum": 45,
        "enum": [
          0,
          6,
          15,
          30,
          45
        ]
      },
      "PrizeExp": {
        "type": "integer",
        "minimum": 480,
        "maximum": 12000,
        "enum": [
          480,
          1800,
          6000,
          12000
        ]
      },
      "PrizeDecoration": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1061,
        "enum": [
          0,
          1051,
          1061
        ]
      },
      "BuffId": {
        "type": "array",
        "minItems": 0,
        "maxItems": 3
      },
      "Photo": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9
        ]
      },
      "RoundPhoto": {
        "type": "string",
        "minLength": 15,
        "maxLength": 20
      }
    },
    "required": [
      "Id",
      "UnlockedStageids",
      "UnlockedNodes",
      "Camp",
      "Seat",
      "Node",
      "Difficulty",
      "General",
      "PrizeMerit",
      "PrizeGold",
      "PrizeIndustry",
      "PrizeEnergy",
      "PrizeTech",
      "PrizeExp",
      "PrizeDecoration",
      "BuffId",
      "Photo",
      "RoundPhoto"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/FrontierStageSetting.json
[
{"Id":10101,"UnlockedStageids":[10102],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":101,"Difficulty":1,"General":21013,"PrizeMerit":1,"PrizeGold":1500,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,2,3],"Photo":2,"RoundPhoto":"campaign_panzer_4"},
{"Id":10102,"UnlockedStageids":[10103],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":101,"Difficulty":1,"General":21035,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":450,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,4,13],"Photo":3,"RoundPhoto":"campaign_panzer_11"},
{"Id":10103,"UnlockedStageids":[10104],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":101,"Difficulty":1,"General":21037,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":90,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[2,3,5],"Photo":7,"RoundPhoto":"campaign_artillery_2"},
{"Id":10104,"UnlockedStageids":[10105],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":101,"Difficulty":1,"General":21037,"PrizeMerit":1,"PrizeGold":1500,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,2,13],"Photo":9,"RoundPhoto":"campaign_defense_2"},
{"Id":10105,"UnlockedStageids":[],"UnlockedNodes":[102],"Camp":1,"Seat":4,"Node":101,"Difficulty":2,"General":21044,"PrizeMerit":2,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":6,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[],"Photo":8,"RoundPhoto":"campaign_artillery_4"},
{"Id":10201,"UnlockedStageids":[10202],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":102,"Difficulty":1,"General":21063,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":450,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,2,3],"Photo":3,"RoundPhoto":"campaign_defense_2"},
{"Id":10202,"UnlockedStageids":[10203],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":102,"Difficulty":1,"General":21063,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":90,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[4,5,13],"Photo":2,"RoundPhoto":"campaign_infantry_3"},
{"Id":10203,"UnlockedStageids":[10204],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":102,"Difficulty":2,"General":21066,"PrizeMerit":1,"PrizeGold":1500,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[2,3,9],"Photo":4,"RoundPhoto":"campaign_artillery_3"},
{"Id":10204,"UnlockedStageids":[10205],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":102,"Difficulty":2,"General":20814,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":450,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[2,5,11],"Photo":7,"RoundPhoto":"campaign_artillery_1"},
{"Id":10205,"UnlockedStageids":[],"UnlockedNodes":[103,201],"Camp":1,"Seat":4,"Node":102,"Difficulty":3,"General":21043,"PrizeMerit":2,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":6,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[],"Photo":8,"RoundPhoto":"campaign_navy_4"},
{"Id":10301,"UnlockedStageids":[10302],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":103,"Difficulty":1,"General":21044,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":90,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,2,11],"Photo":9,"RoundPhoto":"campaign_defense_2"},
{"Id":10302,"UnlockedStageids":[10303],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":103,"Difficulty":2,"General":21127,"PrizeMerit":1,"PrizeGold":1500,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[2,3,13],"Photo":8,"RoundPhoto":"campaign_airforce_5"},
{"Id":10303,"UnlockedStageids":[10304],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":103,"Difficulty":2,"General":21087,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":450,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[4,5,12],"Photo":4,"RoundPhoto":"campaign_panzer_4"},
{"Id":10304,"UnlockedStageids":[10305],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":103,"Difficulty":2,"General":21086,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":90,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[6,11,15],"Photo":7,"RoundPhoto":"campaign_landing_2"},
{"Id":10305,"UnlockedStageids":[10306],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":103,"Difficulty":3,"General":21043,"PrizeMerit":1,"PrizeGold":1500,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,2,13],"Photo":2,"RoundPhoto":"campaign_navy_5"},
{"Id":10306,"UnlockedStageids":[10307],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":103,"Difficulty":3,"General":21036,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":450,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[9,13,15],"Photo":3,"RoundPhoto":"campaign_airforce_3"},
{"Id":10307,"UnlockedStageids":[],"UnlockedNodes":[],"Camp":1,"Seat":4,"Node":103,"Difficulty":4,"General":21044,"PrizeMerit":2,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":6,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[],"Photo":1,"RoundPhoto":"campaign_airforce_1"},
{"Id":20101,"UnlockedStageids":[20102],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":201,"Difficulty":2,"General":21011,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":90,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,2,3],"Photo":5,"RoundPhoto":"campaign_infantry_5"},
{"Id":20102,"UnlockedStageids":[20103],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":201,"Difficulty":2,"General":21031,"PrizeMerit":1,"PrizeGold":1500,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[4,5,6],"Photo":6,"RoundPhoto":"campaign_artillery_2"},
{"Id":20103,"UnlockedStageids":[20104],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":201,"Difficulty":2,"General":21042,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":450,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[7,12,13],"Photo":1,"RoundPhoto":"campaign_artillery_4"},
{"Id":20104,"UnlockedStageids":[20105],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":201,"Difficulty":2,"General":21051,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":90,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,3,15],"Photo":9,"RoundPhoto":"campaign_airforce_4"},
{"Id":20105,"UnlockedStageids":[20106],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":201,"Difficulty":2,"General":20087,"PrizeMerit":1,"PrizeGold":1500,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[9,10,11],"Photo":2,"RoundPhoto":"campaign_navy_4"},
{"Id":20106,"UnlockedStageids":[],"UnlockedNodes":[202],"Camp":2,"Seat":4,"Node":201,"Difficulty":3,"General":29063,"PrizeMerit":2,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":6,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[],"Photo":3,"RoundPhoto":"campaign_panzer_12"},
{"Id":20201,"UnlockedStageids":[20202],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":202,"Difficulty":2,"General":21061,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":450,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,2,3],"Photo":1,"RoundPhoto":"campaign_panzer_3"},
{"Id":20202,"UnlockedStageids":[20203],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":202,"Difficulty":2,"General":21021,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":90,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,7,12],"Photo":3,"RoundPhoto":"campaign_navy_6"},
{"Id":20203,"UnlockedStageids":[20204],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":202,"Difficulty":2,"General":21081,"PrizeMerit":1,"PrizeGold":1500,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,3,15],"Photo":6,"RoundPhoto":"campaign_infantry_6"},
{"Id":20204,"UnlockedStageids":[20205],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":202,"Difficulty":3,"General":25143,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":450,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[9,10,13],"Photo":4,"RoundPhoto":"campaign_airforce_5"},
{"Id":20205,"UnlockedStageids":[20206],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":202,"Difficulty":3,"General":21065,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":90,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[4,5,6],"Photo":5,"RoundPhoto":"campaign_panzer_16"},
{"Id":20206,"UnlockedStageids":[],"UnlockedNodes":[203,301],"Camp":2,"Seat":4,"Node":202,"Difficulty":4,"General":25116,"PrizeMerit":2,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":6,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[],"Photo":9,"RoundPhoto":"campaign_landing_3"},
{"Id":20301,"UnlockedStageids":[20302],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":203,"Difficulty":2,"General":21101,"PrizeMerit":1,"PrizeGold":1500,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,2,13],"Photo":6,"RoundPhoto":"campaign_panzer_2"},
{"Id":20302,"UnlockedStageids":[20303],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":203,"Difficulty":3,"General":21082,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":450,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[4,5,6],"Photo":8,"RoundPhoto":"campaign_panzer_14"},
{"Id":20303,"UnlockedStageids":[20304],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":203,"Difficulty":3,"General":22029,"PrizeMerit":1,"PrizeGold":0,"PrizeIndustry":0,"PrizeEnergy":90,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[9,10,11],"Photo":4,"RoundPhoto":"campaign_infantry_3"},
{"Id":20304,"UnlockedStageids":[20305],"UnlockedNodes":[],"Camp":2,"Seat":4,"Node":203,"Difficulty":3,"General":21085,"PrizeMerit":1,"PrizeGold":1500,"PrizeIndustry":0,"PrizeEnergy":0,"PrizeTech":0,"PrizeExp":480,"PrizeDecoration":0,"BuffId":[1,2,3],"Photo":2,"RoundPhoto":"campaign_defense_1"},
