=== e-gleba/world_conqueror_4_ru/schemas/FrontierNodeSetting.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "FrontierNodeSetting.json",
  "title": "FrontierNodeSetting",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 101,
        "maximum": 1001
      },
      "Chapter": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10
        ]
      },
      "Stageid": {
        "type": "integer",
        "minimum": 10101,
        "maximum": 100101
      },
      "Camp": {
        "type": "integer",
        "minimum": 1,
        "maximum": 6,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6
        ]
      },
      "X": {
        "type": "integer",
        "minimum": 104,
        "maximum": 3441
      },
      "Y": {
        "type": "integer",
        "minimum": 77,
        "maximum": 2185
      },
      "Frame": {
        "type": "integer",
        "minimum": 1,
        "maximum": 8,
        "enum": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ]
      },
      "Sea": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1,
        "enum": [
          0,
          1
        ]
      }
    },
    "required": [
      "Id",
      "Chapter",
      "Stageid",
      "Camp",
      "X",
      "Y",
      "Frame",
      "Sea"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/FrontierNodeSetting.json
[
{"Id":101,"Chapter":1,"Stageid":10101,"Camp":2,"X":2466,"Y":414,"Frame":8,"Sea":0},
{"Id":102,"Chapter":1,"Stageid":10201,"Camp":2,"X":2935,"Y":206,"Frame":2,"Sea":0},
{"Id":103,"Chapter":1,"Stageid":10301,"Camp":2,"X":3441,"Y":340,"Frame":3,"Sea":0},
{"Id":201,"Chapter":2,"Stageid":20101,"Camp":1,"X":2711,"Y":759,"Frame":3,"Sea":0},
{"Id":202,"Chapter":2,"Stageid":20201,"Camp":1,"X":3065,"Y":902,"Frame":4,"Sea":0},
{"Id":203,"Chapter":2,"Stageid":20301,"Camp":1,"X":3320,"Y":642,"Frame":5,"Sea":0},
{"Id":301,"Chapter":3,"Stageid":30101,"Camp":1,"X":2565,"Y":1120,"Frame":7,"Sea":0},
{"Id":302,"Chapter":3,"Stageid":30201,"Camp":1,"X":2441,"Y":1462,"Frame":8,"Sea":0},
{"Id":303,"Chapter":3,"Stageid":30301,"Camp":1,"X":2862,"Y":1352,"Frame":6,"Sea":0},
{"Id":304,"Chapter":3,"Stageid":30401,"Camp":1,"X":3161,"Y":1187,"Frame":8,"Sea":0},
{"Id":305,"Chapter":3,"Stageid":30501,"Camp":1,"X":3289,"Y":1547,"Frame":3,"Sea":0},
{"Id":401,"Chapter":4,"Stageid":40101,"Camp":2,"X":2245,"Y":828,"Frame":2,"Sea":1},
{"Id":402,"Chapter":4,"Stageid":40201,"Camp":2,"X":1944,"Y":1064,"Frame":5,"Sea":1},
{"Id":403,"Chapter":4,"Stageid":40301,"Camp":2,"X":1714,"Y":792,"Frame":4,"Sea":0},
{"Id":404,"Chapter":4,"Stageid":40401,"Camp":2,"X":1676,"Y":1331,"Frame":6,"Sea":1},
{"Id":501,"Chapter":5,"Stageid":50101,"Camp":4,"X":104,"Y":240,"Frame":4,"Sea":0},
{"Id":502,"Chapter":5,"Stageid":50201,"Camp":4,"X":398,"Y":77,"Frame":2,"Sea":0},
{"Id":503,"Chapter":5,"Stageid":50301,"Camp":4,"X":621,"Y":362,"Frame":7,"Sea":0},
{"Id":504,"Chapter":5,"Stageid":50401,"Camp":4,"X":973,"Y":185,"Frame":7,"Sea":0},
{"Id":601,"Chapter":6,"Stageid":60101,"Camp":3,"X":1558,"Y":162,"Frame":4,"Sea":0},
{"Id":602,"Chapter":6,"Stageid":60201,"Camp":3,"X":1886,"Y":327,"Frame":7,"Sea":0},
{"Id":603,"Chapter":6,"Stageid":60301,"Camp":3,"X":2182,"Y":100,"Frame":3,"Sea":0},
{"Id":701,"Chapter":7,"Stageid":70101,"Camp":4,"X":1330,"Y":475,"Frame":1,"Sea":0},
{"Id":702,"Chapter":7,"Stageid":70201,"Camp":4,"X":935,"Y":588,"Frame":6,"Sea":0},
{"Id":703,"Chapter":7,"Stageid":70301,"Camp":4,"X":1251,"Y":803,"Frame":4,"Sea":0},
{"Id":704,"Chapter":7,"Stageid":70401,"Camp":4,"X":1019,"Y":1100,"Frame":1,"Sea":0},
{"Id":801,"Chapter":8,"Stageid":80101,"Camp":3,"X":240,"Y":597,"Frame":5,"Sea":1},
{"Id":802,"Chapter":8,"Stageid":80201,"Camp":3,"X":487,"Y":863,"Frame":4,"Sea":1},
{"Id":803,"Chapter":8,"Stageid":80301,"Camp":3,"X":203,"Y":1068,"Frame":1,"Sea":0},
{"Id":804,"Chapter":8,"Stageid":80401,"Camp":3,"X":593,"Y":1241,"Frame":8,"Sea":1},
{"Id":901,"Chapter":9,"Stageid":90101,"Camp":5,"X":167,"Y":1968,"Frame":4,"Sea":0},
{"Id":902,"Chapter":9,"Stageid":90201,"Camp":5,"X":461,"Y":2185,"Frame":2,"Sea":0},
{"Id":903,"Chapter":9,"Stageid":90301,"Camp":5,"X":792,"Y":1871,"Frame":8,"Sea":0},
{"Id":1001,"Chapter":10,"Stageid":100101,"Camp":6,"X":2686,"Y":1976,"Frame":7,"Sea":1}
]
