=== e-gleba/world_conqueror_4_ru/schemas/TradeTaskSettings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "TradeTaskSettings.json",
  "title": "TradeTaskSettings",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Id": {
        "type": "integer",
        "minimum": 101,
        "maximum": 604,
        "enum": [
          101,
          102,
          103,
          201,
          202,
          203,
          301,
          302,
          303,
          401,
          402,
          403,
          501,
          502,
          503,
          504,
          601,
          602,
          603,
          604
        ]
      },
      "Active": {
        "type": "integer",
        "minimum": 1,
        "maximum": 6,
        "enum": [
          1,
          2,
          3,
          4,
          6
        ]
      },
      "Passive": {
        "type": "integer",
        "minimum": 1,
        "maximum": 7,
        "enum": [
          1,
          2,
          3,
          4,
          7
        ]
      },
      "Base": {
        "type": "integer",
        "minimum": 50,
        "maximum": 10000,
        "enum": [
          50,
          90,
          100,
          170,
          320,
          500,
          2500,
          10000
        ]
      },
      "Get": {
        "type": "integer",
        "minimum": 5,
        "maximum": 37500,
        "enum": [
          5,
          10,
          20,
          25,
          40,
          150,
          200,
          250,
          500,
          1000,
          1250,
          1500,
          2500,
          6250,
          7500,
          12500,
          37500
        ]
      }
    },
    "required": [
      "Id",
      "Active",
      "Passive",
      "Base",
      "Get"
    ],
    "additionalProperties": false
  }
}

=== e-gleba/world_conqueror_4_ru/src/assets/data/TradeTaskSettings.json
[
{"Id":101,"Active":1,"Passive":2,"Base":10000,"Get":1000},
{"Id":102,"Active":1,"Passive":3,"Base":10000,"Get":200},
{"Id":103,"Active":1,"Passive":4,"Base":10000,"Get":20},
{"Id":201,"Active":2,"Passive":1,"Base":2500,"Get":6250},
{"Id":202,"Active":2,"Passive":3,"Base":2500,"Get":250},
{"Id":203,"Active":2,"Passive":4,"Base":2500,"Get":25},
{"Id":301,"Active":3,"Passive":1,"Base":500,"Get":6250},
{"Id":302,"Active":3,"Passive":2,"Base":500,"Get":1250},
{"Id":303,"Active":3,"Passive":4,"Base":500,"Get":25},
{"Id":401,"Active":4,"Passive":1,"Base":100,"Get":12500},
{"Id":402,"Active":4,"Passive":2,"Base":100,"Get":2500},
{"Id":403,"Active":4,"Passive":3,"Base":100,"Get":500},
{"Id":501,"Active":6,"Passive":1,"Base":100,"Get":37500},
{"Id":502,"Active":6,"Passive":2,"Base":100,"Get":7500},
{"Id":503,"Active":6,"Passive":3,"Base":100,"Get":1500},
{"Id":504,"Active":6,"Passive":4,"Base":100,"Get":150},
{"Id":601,"Active":6,"Passive":7,"Base":50,"Get":5},
{"Id":602,"Active":6,"Passive":7,"Base":90,"Get":10},
{"Id":603,"Active":6,"Passive":7,"Base":170,"Get":20},
{"Id":604,"Active":6,"Passive":7,"Base":320,"Get":40}
]
